# DOCKER-VERSION 1.5.0
FROM      postgres
MAINTAINER Sasha Jovicic <sasha.jo@gmail.com>
ENV POSTGRES_PASSWORD="flowsim"
ENV POSTGRES_USER="flowsim"
# expose the working directory, the Back port, the Grunt server port, the SSHD port, and run SSHD
EXPOSE 5432
