
// This is intended to be for testing purposes only. The object
// returned by this module is a mock-database

module.exports = {
  subscribers: [
    {
      email: "jasson.casey@gmail.com",
      password: "iluvflowg",
      reg_date: "",
      reg_ip: "",
      state: "",                        // CREATED | ACTIVE | RESET | CLOSED,
      token: ""                         // large random number .. verification/reset token
    }
  ],
  sessions: [
    {
      begin_time: "",           // set by creating the entry
      src_ip: "",               // source address of the session
      state: "",                // ACTIVE | AUTHENTICATED | LOGGEDOUT | TIMEDOUT
      logout_time: "",          // set by logout or timeout
      subscriberId: 2,          // sub ref, may be null if not authenticated
      accessToken: 'asdfasdf'   // generated by login, cleared by logout or timeout
    }
  ]
}

